### ISSUE TITLE
Write out json file with attributes: extracted_text, filename, region_start, region_end, label

### ISSUE THREAD

**Issue by eglassman** [eglassman/prose#3]

**Comment by eglassman** [comment]
Label examples:
Header (optional parent nodes)
Body (optional parent nodes)
Aux js library load
d3 library load
style
d3 data load callback
d3 load argument

**Comment by eglassman** [comment]
@Steven-Hewitt, in the code you committed in order to close #4, there was an example of a label for the data load callback. That's where a lot of the heart of d3 code lives. I would prioritize getting program synthesis to learn *that* label, first. If you then create this JSON for all the 50 files and the data-load-callback label, we can use that to programmatically insert that class in spans around the callbacks in our index50.html file (therefore addressing and closing #2).

**Comment by eglassman** [comment]
I just committed my updates to the VS Solution file so it writes out of a csv-like thing to the console, which I'm going to use as a starting point for more rendering explorations.

**Comment by eglassman** [comment]
Okay, this is what I'll do next. Stealing this back from you. ;)

**Comment by eglassman** [comment]
Wrote out data in json-like format to console. Still needs to be saved as json file by hand, but I think that shouldn't be automated yet.

**Comment by eglassman** [comment]
Unfortunately, it's not well-formed JSON. It doesn't have \n where it should: 
![image](https://cloud.githubusercontent.com/assets/2320194/22685103/d98d9d7a-ecd3-11e6-813b-4906f2739ef4.png)

Trying to write out the json now using http://stackoverflow.com/questions/16921652/how-to-write-a-json-file-in-c

**Comment by eglassman** [comment]
@Steven-Hewitt I got stuck trying to write out well-formed JSON files with multiple line values. It's not completely necessary, though. I'll continue without it for now. If you can figure out how to do it, can you show me how?

**Comment by Steven-Hewitt** [comment]
Sounds good, I'll try to do that before I go to sleep tonight.  If not, first thing tomorrow.

**Comment by eglassman** [comment]
While this wasn't necessary to complete my simplest prototype tonight, it will be really helpful to have this, for debugging and additional prototyping purposes. Thanks in advance, @Steven-Hewitt!

**Comment by eglassman** [comment]
I updated the title of this issue to reflect the fact that the critical missing pieces are
- [ ] write json file so I don't have to keep copying and pasting console.log print outs
- [ ] add html-escaped, correctly multi-lined extracted text to each extracted item in the json list

**Comment by Steven-Hewitt** [comment]
I think I'm done, but my tests are getting caught up on a thing that didn't seem to be an issue when you were running the code during our meeting where `LearnHTMLlang` is failing to actually learn.

Don't feel comfortable uploading/closing issue until I have that worked out, but hopefully that'll be soon.

![image](https://cloud.githubusercontent.com/assets/20484717/22709522/eb9adf72-ed2e-11e6-862c-3ba19203fd7a.png)

**Comment by eglassman** [comment]
@Steven-Hewitt Weird, okay! Want to swing by my desk and we can look at it together? Andrew and Gustavo are also comfortable with C# --> JSON.

**Comment by Steven-Hewitt** [comment]
@eglassman Sure! Since I'm working from my desktop, I'll get the current updates on my laptop so that I can check in tomorrow (or, failing that, set up VNC so I can remotely connect).

**Comment by eglassman** [comment]
@Steven-Hewitt I'm here in the lab until 5. Want to swing by? In the meantime, I've sent a message about this to Andrew and Gustavo.

**Comment by eglassman** [comment]
@Steven-Hewitt Gustavo's response:

var submissionsToJson = JsonConvert.SerializeObject(submissions);
               File.WriteAllText("submissionsResults.json", submissionsToJson);

In the meantime, I'm printing to the console stuff that I can copy and paste into a file for prototyping purposes.

**Comment by Steven-Hewitt** [comment]
Sorry I missed you! By the time I saw your message, I was already in a class that lasted until after 5.  Do you have time tomorrow?  If so, can you tell me (preferably by tonight) what time you're free so I can drop by then?

**Comment by eglassman** [comment]
I’m free noon to 2 and 3:30 to 5ish. Swing by! I’ll have news from meeting with Bjoern and Marti. :)

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.4.52&pv=10.12.3&source=email_footer_2]
On Wed, Feb 8, 2017 at 10:03 PM, Steven Hewitt <notifications@github.com> wrote:
Sorry I missed you! By the time I saw your message, I was already in a class that lasted until after 5. Do you have time tomorrow? If so, can you tell me (preferably by tonight) what time you're free so I can drop by then?

**Comment by Steven-Hewitt** [comment]
Sounds good!

**Comment by Steven-Hewitt** [comment]
I'm heading out soon, and will probably be there sometime close to 12, 12:30.

**Comment by eglassman** [comment]
I'm getting lunch to go, will be back in lab shortly. Meeting with Bjoern and Marti went well. Made a lot of progress last night. Much more to do, the deadline is less than 2 months away!!


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.3.59&pv=7.1.1&source=email_footer_2] On Thu, Feb 09, 2017 at 11:13am, Steven Hewitt < notifications@github.com [notifications@github.com] > wrote:
I'm heading out soon, and will probably be there sometime close to 12, 12:30.

**Comment by Steven-Hewitt** [comment]
Sounds good.  I'm in lab, had to nuke my VS install though so it's reinstalling right now.

**Comment by eglassman** [comment]
Done.
