### ISSUE TITLE
Turns out that browsers *do* make their fixed-up html available!

### ISSUE THREAD

**Issue by eglassman** [eglassman/prose#5]
My index.html does not have header and body tags, but the html DOM in the console does! 

If we have trouble reliably learning interesting aspects of d3 examples because of html code that's not fixed up by a browser, maybe we can take advantage of this.
![image](https://cloud.githubusercontent.com/assets/2320194/22533070/8ee4ece2-e8a0-11e6-8095-acd15bc80b70.png)

**Comment by Steven-Hewitt** [comment]
If we can get it to not choke up on malformed HTML, though, all the better.

**Comment by eglassman** [comment]
I've thought about this a little more... It is not so simple. Let's proceed without it, for now. This will not help us with the central code: D3 scripts.

**Comment by eglassman** [comment]
However, programmatically analyzing the d3 code *AND* the DOM that it creates? Now that might give us a better handle on things, if we need it. :)

If different d3 code creates the same effect in the DOM, it helps to know that.

**Comment by eglassman** [comment]
This is not really an 'issue' just an observation so I'm closing this.
